### ISSUE TITLE
Packaging output not working on macOS

### ISSUE THREAD

**Issue by galderz** [graalvm/mandrel-packaging#42]
Mandrel not fully working when built on macOS.

Fixes in https://github.com/graalvm/mandrel-packaging/pull/40 made the build finish, but the end product is not yet working. Even with libffi installed (e.g. via `brew install libffi`), `ffi.h` is not found.

```
[debug-info-1.0.0-SNAPSHOT-runner:97500]        setup:   2,461.61 ms,  0.96 GB
Error: Error compiling query code (in /var/folders/_8/yr2jgs8x5pq4vl79ydvq7nv00000gn/T/SVM-4297529153662705686/LibFFIHeaderDirectives.c). Compiler command '/usr/bin/cc -I/Users/g/.qollider/cache/2406/graalvm_home/lib/svm/clibraries/darwin-amd64/include -o /var/folders/_8/yr2jgs8x5pq4vl79ydvq7nv00000gn/T/SVM-4297529153662705686/LibFFIHeaderDirectives /var/folders/_8/yr2jgs8x5pq4vl79ydvq7nv00000gn/T/SVM-4297529153662705686/LibFFIHeaderDirectives.c ' output included error: /Users/g/.qollider/cache/2406/graalvm_home/lib/svm/clibraries/darwin-amd64/include/svm_libffi.h:25:10: fatal error: 'ffi.h' file not found
com.oracle.svm.core.util.UserError$UserException: Error compiling query code (in /var/folders/_8/yr2jgs8x5pq4vl79ydvq7nv00000gn/T/SVM-4297529153662705686/LibFFIHeaderDirectives.c). Compiler command '/usr/bin/cc -I/Users/g/.qollider/cache/2406/graalvm_home/lib/svm/clibraries/darwin-amd64/include -o /var/folders/_8/yr2jgs8x5pq4vl79ydvq7nv00000gn/T/SVM-4297529153662705686/LibFFIHeaderDirectives /var/folders/_8/yr2jgs8x5pq4vl79ydvq7nv00000gn/T/SVM-4297529153662705686/LibFFIHeaderDirectives.c ' output included error: /Users/g/.qollider/cache/2406/graalvm_home/lib/svm/clibraries/darwin-amd64/include/svm_libffi.h:25:10: fatal error: 'ffi.h' file not found
	at com.oracle.svm.core.util.UserError.abort(UserError.java:135)
	at com.oracle.svm.hosted.c.NativeLibraries.reportErrors(NativeLibraries.java:336)
	at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1528)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1027)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:856)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:536)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1

**Comment by zakkak** [comment]
@galderz is this a packaging issue or a mandrel issue? i.e. if you build without mandrel-packaging's buildJDK does it work?

**Comment by galderz** [comment]
@zakkak Works without mandrel-packaging. The original build includes sorting out ffi, but mandrel-packaging is depending on the system level ffi setup, as described [here](https://github.com/graalvm/mandrel/blame/master/README-Mandrel.md#L43). I'll ping you to discuss options.

**Comment by galderz** [comment]
On macOS `/usr/include` does not exist. Setting somehow `CPATH` might work (see [here](https://apple.stackexchange.com/questions/372032/usr-include-missing-on-macos-catalina-with-xcode-11)), but that'd need to happen by `native-image`, a wrapper or in code.
