### ISSUE TITLE
Support building Mandrel on aarch64

### ISSUE THREAD

**Issue by galderz** [graalvm/mandrel-packaging#55]
Fails with:

```
cp: cannot stat '/home/g/.qollider/cache/2008/mandrel/substratevm/mxbuild/linux-amd64/src/com.oracle.svm.native.libchelper/amd64/liblibchelper.a': No such file or directory
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(qollider.java:1532)
	at Steps$Exec.run(qollider.java:1197)
	at Mandrel.build(qollider.java:691)
	at SystemMandrel.build(qollider.java:641)
	at qollider.main(qollider.java:91)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(qollider.java:1526)
	... 4 more
```

`buildJDK.sh` is assuming `amd64`, see [here](https://github.com/graalvm/mandrel-packaging/blob/master/buildJDK.sh#L95).

**Comment by Karm** [comment]
The build works: https://karms.biz/tmp/mandrel-java11-linux-aarch64-20.2-SNAPSHOT.tarxz
What we need now is a CI setup. Then this issue can be closed.

**Comment by Karm** [comment]
This issue is alive and kicking :)
