### ISSUE TITLE
Building Graal master keeps failing /tracking issue/

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel-packaging#74]
# GitHub actions
```

[wrote /home/runner/work/mandrel-packaging/mandrel-packaging/mandrel/substratevm/mxbuild/src/com.oracle.svm.jni/bin/com/oracle/svm/jni/access/Plugin_JNIAccessFeature_haveJavaRuntimeReflectionSupport.class]
[checking com.oracle.svm.jni.access.PluginReplacementNode_JNIAccessFeature_haveJavaRuntimeReflectionSupport]
[loading /home/runner/work/mandrel-packaging/mandrel-packaging/mandrel/compiler/mxbuild/dists/jdk11/graal.jar(/org/graalvm/compiler/graph/NodeList.class)]
[loading /home/runner/work/mandrel-packaging/mandrel-packaging/mandrel/compiler/mxbuild/dists/jdk11/graal.jar(/org/graalvm/compiler/graph/iterators/NodeIterable.class)]
[wrote /home/runner/work/mandrel-packaging/mandrel-packaging/mandrel/substratevm/mxbuild/src/com.oracle.svm.jni/bin/com/oracle/svm/jni/access/PluginReplacementNode_JNIAccessFeature_haveJavaRuntimeReflectionSupport.class]
[checking com.oracle.svm.jni.access.Plugin_JNIAccessFeature_singleton]
[wrote /home/runner/work/mandrel-packaging/mandrel-packaging/mandrel/substratevm/mxbuild/src/com.oracle.svm.jni/bin/com/oracle/svm/jni/access/Plugin_JNIAccessFeature_singleton.class]
[checking com.oracle.svm.jni.access.PluginReplacementNode_JNIAccessFeature_singleton]
[wrote /home/runner/work/mandrel-packaging/mandrel-packaging/mandrel/substratevm/mxbuild/src/com.oracle.svm.jni/bin/com/oracle/svm/jni/access/PluginReplacementNode_JNIAccessFeature_singleton.class]
[checking com.oracle.svm.jni.access.PluginFactory_JNIAccessFeature]
[wrote /home/runner/work/mandrel-packaging/mandrel-packaging/mandrel/substratevm/mxbuild/src/com.oracle.svm.jni/bin/com/oracle/svm/jni/access/PluginFactory_JNIAccessFeature.class]
[total 842ms]
Result = 0
Compiling com.oracle.svm.graal with javac-daemon(JDK 11) failed
Shutting down
Shutting down
  File "/home/runner/work/mandrel-packaging/mandrel-packaging/mx/mx.py", line 17180, in <module>
    main()
  File "/home/runner/work/mandrel-packaging/mandrel-packaging/mx/mx.py", line 17161, in main
    retcode = c(command_args)
  File "/home/runner/work/mandrel-packaging/mandrel-packaging/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/home/runner/work/mandrel-packaging/mandrel-packaging/mx/mx.py", line 13946, in build
    abort('{0} build tasks failed'.format(len(failed)))
  File "/home/runner/work/mandrel-packaging/mandrel-packaging/mx/mx.py", line 3912, in abort
    traceback.print_stack()
1 build tasks failed
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
  at OperatingSystem.exec(build.java:1620)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
  at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
  at Mx.build(build.java:677)
  at SequentialBuild.build(build.java:494)
  at build.main(build.java:62)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
  at OperatingSystem.exec(build.java:1611)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
  at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
  at Mx.build(build.java:677)
  at SequentialBuild.build(build.java:494)
  at build.main(build.java:62)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
  at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
  at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
Error: Process completed with exit code 1.
```

# Jenkins
```
03:41:07 INFO [build] Building!
03:41:13 Note: /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mx/java/ListModules.java uses unchecked or unsafe operations.
03:41:13 Note: Recompile with -Xlint:unchecked for details.
03:41:49 Note: /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/JavaLangSubstitutions.java uses or overrides a deprecated API that is marked for removal.
03:41:49 Note: Recompile with -Xlint:removal for details.
03:41:54 /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationReason.java:41: error: cannot find symbol
03:41:54     public SpeculationLog.SpeculationReasonEncoding encode(Supplier<SpeculationLog.SpeculationReasonEncoding> encodingSupplier) {
03:41:54                                                                                   ^
03:41:54   symbol:   class SpeculationReasonEncoding
03:41:54   location: interface SpeculationLog
03:41:54 /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationReason.java:41: error: cannot find symbol
03:41:54     public SpeculationLog.SpeculationReasonEncoding encode(Supplier<SpeculationLog.SpeculationReasonEncoding> encodingSupplier) {
03:41:54                          ^
03:41:54   symbol:   class SpeculationReasonEncoding
03:41:54   location: interface SpeculationLog
03:41:54 /home/jenkins/jenkins/workspace/mandrel-master-linux-build/mandrel/substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/isolated/IsolatedSpeculationReasonEncoding.java:40: error: cannot find symbol
03:41:54 final class IsolatedSpeculationReasonEncoding extends ByteArrayOutputStream implements SpeculationLog.SpeculationReasonEncoding {
03:41:54                                                                                                      ^
03:41:54   symbol:   class SpeculationReasonEncoding
03:41:54   location: interface SpeculationLog
03:41:54 3 errors
03:41:54 
03:41:54 Compiling com.oracle.svm.graal with javac-daemon(JDK 11) failed
03:41:54 1 build tasks failed
03:41:54 Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
03:41:54 	at OperatingSystem.exec(build.java:1484)
03:41:54 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
03:41:54 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
03:41:54 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
03:41:54 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
03:41:54 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
03:41:54 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
03:41:54 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
03:41:54 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
03:41:54 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
03:41:54 	at Mx.build(build.java:567)
03:41:54 	at SequentialBuild.build(build.java:402)
03:41:55 	at build.main(build.java:56)
03:41:55 Caused by: java.lang.RuntimeException: Failed, exit code: 1
03:41:55 	at OperatingSystem.exec(build.java:1475)
03:41:55 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
03:41:55 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
03:41:55 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
03:41:55 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
03:41:55 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
03:41:55 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
03:41:55 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
03:41:55 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
03:41:55 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
03:41:55 	at Mx.build(build.java:567)
03:41:55 	at SequentialBuild.build(build.java:402)
03:41:55 	at build.main(build.java:56)
03:41:55 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:41:55 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03:41:55 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:41:55 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
03:41:55 	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
03:41:55 	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
03:41:55 	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
```

**Comment by zakkak** [comment]
@Karm this is not mandrel-packaging related and is being tracked in https://github.com/graalvm/mandrel/issues/146

**Comment by jerboaa** [comment]
Fixed with: https://github.com/oracle/graal/pull/2945
